<?php
/**
 * Helpers class to do Add Schema for WP Travel Pages.
 *
 * @package WP_Travel
 */

/**
 * Schema Helper.
 */
class WpTravel_Helpers_Schema {

	/**
	 * This variable include trip data which is used in schema.
	 *
	 * @var array $trip
	 */
	public static $trip;

	/**
	 * Initialize schema in WP Travel.
	 *
	 * @since 5.0.0
	 */
	public static function init() {
		add_action( 'wp_head', array( __CLASS__, 'run' ) );
	}

	/**
	 * Display all available schema for WP Travel.
	 *
	 * @since 5.0.0
	 */
	public static function run() {
		$use_schema = apply_filters( 'wptravel_use_schema', true );
		if ( ! $use_schema ) {
			return;
		}
		if ( WP_Travel::is_page( 'single' ) ) {
			global $post;
			$trip_id   = $post->ID;
			$trip_data = WpTravel_Helpers_Trips::get_trip( $trip_id );
			$trip      = array();
			if ( is_array( $trip_data ) && ! is_wp_error( $trip_data ) && isset( $trip_data['code'] ) && 'WP_TRAVEL_TRIP_INFO' === $trip_data['code'] ) {
				$trip = $trip_data['trip'];
			}
			self::$trip = $trip;
		}
		self::get_trip_schema();

		if ( WP_Travel::is_page( 'single' ) ) {
			self::get_faq_schema( $trip_id );
		}
	}

	public static function get_trip_schema() {

		if ( ! self::$trip ) {
			return;
		}

		$trip    = self::$trip;
		$trip_id = $trip['id'];

		/**
		 * Base Schema
		 */
		$schema = array(
			'@context' => 'https://schema.org',
			'@type'    => 'TouristTrip',

			'name' => isset( $trip['title'] )
				? ucwords( $trip['title'] )
				: '',

			'description' => isset( $trip['trip_overview'] )
				? wp_strip_all_tags( $trip['trip_overview'] )
				: '',

			'url' => isset( $trip['url'] )
				? $trip['url']
				: '',

			'identifier' => array(
				'@type' => 'PropertyValue',
				'name'  => 'Trip ID',
				'value' => $trip_id,
			),
		);


		/**
		 * Filter
		 */
		$schema = apply_filters(
			'wp_travel_trip_schema',
			$schema,
			$trip_id,
			$trip
		);

		self::generate_schema( $schema );
	}

	/**
	 * Generate FAQ Schema.
	 *
	 * @param int $trip_id Trip ID.
	 */
	public static function get_faq_schema( $trip_id ) {

		$faq_items = array();

		$faq_items = apply_filters(
						'wp_travel_faq_schema_items',
						$faq_items,
						$trip_id
					);

		if ( empty( $faq_items ) ) {
			return;
		}

		$schema = array(
			'@context' => 'https://schema.org',
			'@type'    => 'FAQPage',
			'mainEntity' => $faq_items,
		);

		self::generate_schema( $schema );
	}

	/**
	 * Generate schema as per $schema array.
	 *
	 * @since 5.0.0
	 * @param array $schema Schema structure array.
	 * @return string
	 */
	public static function generate_schema( $schema = array() ) {
		if ( ! $schema ) {
			return;
		}

		$schema_structure = '';

		if ( $schema ) {
			$schema_structure .= "\n\n";
			$schema_structure .= '<!-- This schema is generated by WP Travel v' . WP_TRAVEL_VERSION . ' -->';
			$schema_structure .= "\n";
			$schema_structure .= '<script type="application/ld+json">' . wp_json_encode( $schema, JSON_UNESCAPED_UNICODE ) . '</script>';
			$schema_structure .= "\n\n";
		}
		echo $schema_structure; // @phpcs:ignore
	}

}
WpTravel_Helpers_Schema::init();
